import React from "react";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import WhyTrust from "@/components/whytrust";
import BelowTrust from "@/components/belowtrust";
import WhatWeDo from "@/components/whatwedo";
import EstateFolderSection from "@/components/EstateFolderSection";
import Process from "@/components/process";
import EstateComparison from "@/components/EstateComparison";
import Pricing from "@/components/pricing";
import Testimonial from "@/components/testimonial";
import FAQ from "@/components/faq";
import CTA from "@/components/cta";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    absolute: "WillDrafting.in — Legally Valid Online Will in Minutes",
  },
  description:
    "Draft your legally valid Will online in minutes under the Indian Succession Act. Enter details, download court-ready printout & register hassle-free.",
  alternates: {
    canonical: "https://www.willdrafting.in",
  },
  openGraph: {
    title: "WillDrafting.in — Legally Valid Online Will in Minutes",
    description:
      "Draft your legally valid Will online in minutes under the Indian Succession Act. Enter details, download court-ready printout & register hassle-free.",
    url: "https://www.willdrafting.in",
    siteName: "WillDrafting.in",
    locale: "en_IN",
    type: "website",
    images: [
      {
        url: "/desktopusp.jpg",
        width: 1200,
        height: 630,
        alt: "WillDrafting.in - Legally Valid Online Wills in Minutes",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "WillDrafting.in — Legally Valid Online Will in Minutes",
    description:
      "Draft your legally valid Will online in minutes under the Indian Succession Act. Enter details, download court-ready printout & register hassle-free.",
    images: ["/desktopusp.jpg"],
  },
};

const HOME_FAQ_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "How does WillDrafting.in work?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "You answer simple, step-by-step questions about yourself, your family, and your assets. In less than 15 minutes, our legal engine generates a complete, legally formatted, court-ready Will compliant with the Indian Succession Act, 1925, ready for instant download.",
      },
    },
    {
      "@type": "Question",
      "name": "How do I print, sign, and execute my Will after completing it online?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Once you complete the questions, download your court-ready PDF immediately. Print it on standard plain A4 paper, sign each page at the bottom, and have two independent adult witnesses sign in your physical presence. We provide clear, step-by-step attestation instructions with every document.",
      },
    },
    {
      "@type": "Question",
      "name": "Can I take this printed Will and get it registered without any hassle?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Yes, absolutely. The Will generated by WillDrafting.in strictly adheres to all statutory formatting standards required by Sub-Registrars under the Registration Act, 1908. You can take the printed document directly to your local Sub-Registrar's office with your two witnesses without needing any middleman.",
      },
    },
    {
      "@type": "Question",
      "name": "How long does it take to create a Will on WillDrafting.in?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Most users complete their Will questionnaire in 10 to 15 minutes. There is no waiting for manual law firm appointments or weeks of back-and-forth drafts—your document is generated instantly.",
      },
    },
    {
      "@type": "Question",
      "name": "What information should I have ready before starting?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "You only need basic details: your contact information, names of family members or beneficiaries, a list of your assets (property addresses, bank accounts, Demat folios, mutual funds, vehicles), and the names of your preferred executor and guardian for minor children.",
      },
    },
    {
      "@type": "Question",
      "name": "Can I make changes or update my Will later if my assets change?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Yes. Your Will is stored securely in your private WillDrafting account. Whenever your family or financial circumstances change—such as buying a new property or opening new investments—you can log in, update your details, and download an updated draft.",
      },
    },
    {
      "@type": "Question",
      "name": "Is my personal and asset information private and secure?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Yes. We employ bank-grade 256-bit encryption for all data in transit and at rest. Your confidential family details, asset folios, and testamentary wishes are strictly protected and never shared with third parties.",
      },
    },
    {
      "@type": "Question",
      "name": "How is WillDrafting.in different from hiring an expensive traditional lawyer?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Traditional law firms often require multiple physical visits and take weeks. WillDrafting.in delivers the exact same statutory legal clauses and court-ready precision online in minutes with instant print-ready download and registration guidance.",
      },
    },
    {
      "@type": "Question",
      "name": "Are Demat shares, mutual funds, bank accounts, and jewellery covered?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Yes. Our questionnaire includes dedicated modules for real estate, bank deposits, Demat portfolios, mutual funds, insurance policies, business shares, motor vehicles, digital accounts, and personal jewellery.",
      },
    },
    {
      "@type": "Question",
      "name": "Can I reach out to legal support if I have questions while drafting?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text":
          "Yes. Our legal advisory team is available via chat, email, and phone (+91 98200 98765) to assist you with executor selection, clause allocation, or registration guidance whenever you need help.",
      },
    },
  ],
};

export default function Home() {
  return (
    <div style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(HOME_FAQ_SCHEMA) }}
      />
      <Navbar />
      <main style={{ flex: "1 0 auto" }}>
        <Hero />
        <WhyTrust />
        <BelowTrust />
        <WhatWeDo />
        <EstateFolderSection />
        <Process />
        <EstateComparison />
        <Pricing />
        <Testimonial />
        <FAQ />
        <CTA />
      </main>
      <Footer />
    </div>
  );
}
