"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

interface FAQItem {
  id: number;
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    id: 1,
    question: "How does WillDrafting.in work?",
    answer:
      "You answer simple, step-by-step questions about yourself, your family, and your assets. In less than 15 minutes, our legal engine generates a complete, legally formatted, court-ready Will ready for instant download.",
  },
  {
    id: 2,
    question: "How do I print, sign, and execute my Will after completing it online?",
    answer:
      "Once you complete the questions, download your court-ready PDF immediately. Print it on standard plain A4 paper, sign each page at the bottom, and have two independent adult witnesses sign in your physical presence. We provide clear, step-by-step attestation instructions with every document.",
  },
  {
    id: 3,
    question: "Can I take this printed Will and get it registered without any hassle?",
    answer:
      "Yes, absolutely. The Will generated by WillDrafting.in strictly adheres to all statutory formatting standards required by Sub-Registrars under the Registration Act, 1908. You can take the printed document directly to your local Sub-Registrar's office with your two witnesses without needing any middleman.",
  },
  {
    id: 4,
    question: "How long does it take to create a Will on WillDrafting.in?",
    answer:
      "Most users complete their Will questionnaire in 10 to 15 minutes. There is no waiting for manual law firm appointments or weeks of back-and-forth drafts—your document is generated instantly.",
  },
  {
    id: 5,
    question: "What information should I have ready before starting?",
    answer:
      "You only need basic details: your contact information, names of family members or beneficiaries, a list of your assets (property addresses, bank accounts, Demat folios, mutual funds, vehicles), and the names of your preferred executor and guardian for minor children.",
  },
  {
    id: 6,
    question: "Can I make changes or update my Will later if my assets change?",
    answer:
      "Yes. Your Will is stored securely in your private WillDrafting account. Whenever your family or financial circumstances change—such as buying a new property or opening new investments—you can log in, update your details, and download an updated draft.",
  },
  {
    id: 7,
    question: "Is my personal and asset information private and secure?",
    answer:
      "Yes. We employ bank-grade 256-bit encryption for all data in transit and at rest. Your confidential family details, asset folios, and testamentary wishes are strictly protected and never shared with third parties.",
  },
  {
    id: 8,
    question: "How is WillDrafting.in different from hiring an expensive traditional lawyer?",
    answer:
      "Traditional law firms often require multiple physical visits and take weeks. WillDrafting.in delivers the exact same statutory legal clauses and court-ready precision online in minutes with instant print-ready download and registration guidance.",
  },
  {
    id: 9,
    question: "Are Demat shares, mutual funds, bank accounts, and jewellery covered?",
    answer:
      "Yes. Our questionnaire includes dedicated modules for real estate, bank deposits, Demat portfolios, mutual funds, insurance policies, business shares, motor vehicles, digital accounts, and personal jewellery.",
  },
  {
    id: 10,
    question: "Can I reach out to legal support if I have questions while drafting?",
    answer:
      "Yes. Our legal advisory team is available via chat, email, and phone (+91 98200 98765) to assist you with executor selection, clause allocation, or registration guidance whenever you need help.",
  },
];

export default function FAQ() {
  // Item 2 is open by default to highlight the instant print & register USP
  const [openId, setOpenId] = useState<number | null>(2);

  const toggleFAQ = (id: number) => {
    setOpenId((prev) => (prev === id ? null : id));
  };

  return (
    <section className="w-full bg-[#FAF7F0] py-16 sm:py-24 lg:py-28 flex justify-center">
      <div className="w-full max-w-[1400px] mx-auto px-6 sm:px-8 lg:px-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-start">
          
          {/* =========================================================================
              LEFT COLUMN: Eyebrow, Editorial Heading, and Desktop Card
              ========================================================================= */}
          <div className="lg:col-span-5 flex flex-col justify-between h-full">
            <div>
              {/* Eyebrow badge */}
              <div className="flex items-center gap-2 mb-5 sm:mb-6">
                <span className="text-[0.75rem] font-bold tracking-[0.16em] uppercase text-[#C65378]">
                  Product & Process FAQ
                </span>
              </div>

              {/* Main Headline */}
              <h2 className="text-[2.2rem] sm:text-[3rem] lg:text-[3.4rem] font-medium text-[#111827] leading-[1.12] tracking-tight mb-6">
                Everything you need to know about our platform.
              </h2>

              <p className="text-[0.98rem] sm:text-[1.05rem] leading-[1.65] text-[#55636D] max-w-[420px] mb-8">
                Learn how WillDrafting.in lets you enter details, download court-ready printouts in minutes, and register your Will without confusion or delays.
              </p>
            </div>

            {/* Support Card on Left */}
            <div className="bg-white rounded-2xl p-6 sm:p-7 border border-[#172228]/10 shadow-xs max-w-[420px]">
              <h3 className="text-base font-semibold text-[#111827] mb-2">
                Have a specific question about your estate?
              </h3>
              <p className="text-xs text-[#55636D] leading-relaxed mb-5">
                Our legal team is here to assist with drafting, executor nominations, and registration guidance.
              </p>
              <Link
                href="/contact"
                className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#172228] hover:text-[#C65378] transition-colors group"
              >
                <span>Talk to our legal desk</span>
                <ArrowUpRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
              </Link>
            </div>
          </div>

          {/* =========================================================================
              RIGHT COLUMN: Interactive Accordion List
              ========================================================================= */}
          <div className="lg:col-span-7 divide-y divide-[#172228]/10 border-t border-b border-[#172228]/10">
            {faqs.map((faq) => {
              const isOpen = openId === faq.id;
              return (
                <div key={faq.id} className="py-5 sm:py-6 transition-colors">
                  <button
                    onClick={() => toggleFAQ(faq.id)}
                    className="w-full flex items-center justify-between text-left gap-4 group cursor-pointer focus:outline-hidden"
                    aria-expanded={isOpen}
                  >
                    <span className="text-[1.08rem] sm:text-[1.2rem] font-medium text-[#111827] group-hover:text-[#C65378] transition-colors duration-200">
                      {faq.question}
                    </span>
                    <span
                      className={`shrink-0 w-8 h-8 rounded-full border border-[#172228]/15 flex items-center justify-center text-[#172228] transition-transform duration-300 ${
                        isOpen ? "rotate-45 bg-[#C65378] border-[#C65378] text-white" : "bg-white"
                      }`}
                    >
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <line x1="12" y1="5" x2="12" y2="19" />
                        <line x1="5" y1="12" x2="19" y2="12" />
                      </svg>
                    </span>
                  </button>

                  {isOpen && (
                    <div className="pt-4 pr-10 text-[0.94rem] sm:text-[1rem] leading-[1.7] text-[#55636D] animate-fadeIn">
                      <p>{faq.answer}</p>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
